# Generated by Django 3.2.7 on 2023-06-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('time_taken', models.IntegerField(default=0)),
            ],
        ),
    ]
