# Generated by Django 3.2.7 on 2023-07-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_taken',
            field=models.DateTimeField(),
        ),
    ]
