# Generated by Django 3.2.7 on 2023-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_entry_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_taken',
            field=models.CharField(max_length=50),
        ),
    ]
